kind: Grafana
apiVersion: grafana.integreatly.org/v1beta1
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: maas-api
spec:
  config:
    auth:
      disable_login_form: 'false'
    log:
      mode: console
    security:
      # Default credentials - change after first login
      admin_user: admin
      admin_password: admin
  deployment:
    spec:
      template:
        metadata:
          # Disable Istio sidecar injection for Grafana in current implementation
          annotations:
            sidecar.istio.io/inject: "false" 