apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- telemetry-policy.yaml
- prometheus-servicemonitors.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: maas-observability
