apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maas-api

resources:
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - prometheus-rbac.yaml
  - models-aas-servicemonitor.yaml
  - kuadrant-servicemonitors.yaml

labels:
  - pairs:
      environment: base
      project: models-aas-observability
