---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-api-ca-cert
  namespace: kuadrant-system
data:
  ca-bundle.crt: |
    # This will be populated by the create-maas-api-cert.sh script
    # The CA certificate content goes here