apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/maas-api/overlays/tls  
  - ../../base/policies               
  - service-ca-bundle.yaml
  - envoyfilter-authorino-tls.yaml    

patches:
  - target:
      group: kuadrant.io
      version: v1
      kind: AuthPolicy
      name: gateway-auth-policy
    path: patches/authpolicy-https.yaml
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: maas-api-route
    patch: |-
      - op: replace
        path: /spec/rules/0/backendRefs/0/port
        value: 8443
      - op: replace
        path: /spec/rules/1/backendRefs/0/port
        value: 8443
